apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-examen
  labels:
    name: despliegue-examen
    app: kube-examen
spec:
  replicas: 1
  selector:
    matchLabels:
      name: testing-kube-examen
      app: kube-examen
  template:
    metadata:
      name: testing-kube-examen
      labels:
        name: testing-kube-examen
        app: kube-examen
    spec:
      containers:
        - name: kube-container-examen
          image: "141861444441.dkr.ecr.us-east-1.amazonaws.com/examen1-front:latest"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          livenessProbe:
            httpGet:
              path: /estoyvivo
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5