apiVersion: v1
kind: Service
metadata:
  name: servicio-examen
  labels:
    name: despliegue-examen
    app: kube-examen
spec:
  type: NodePort
  selector:
    app: kube-examen
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30010
